const avatar = [
  "https://st.kp.yandex.net/images/sm_actor/558099.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1054956.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2286874.jpg",
  "https://st.kp.yandex.net/images/sm_actor/231512.jpg",
  "https://st.kp.yandex.net/images/sm_actor/224384.jpg",
  "https://st.kp.yandex.net/images/sm_actor/273292.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2460349.jpg",
  "https://st.kp.yandex.net/images/sm_actor/551325.jpg",
  "https://st.kp.yandex.net/images/sm_actor/224620.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1193331.jpg",
  "https://st.kp.yandex.net/images/sm_actor/752.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1714177.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1959253.jpg",
  "https://st.kp.yandex.net/images/sm_actor/52108.jpg",
  "https://st.kp.yandex.net/images/sm_actor/733.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1258688.jpg",
  "https://st.kp.yandex.net/images/sm_actor/42164.jpg",
  "https://st.kp.yandex.net/images/sm_actor/231517.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1555520.jpg",
  "https://st.kp.yandex.net/images/sm_actor/3429664.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1762044.jpg",
  "https://st.kp.yandex.net/images/sm_actor/594053.jpg",
  "https://st.kp.yandex.net/images/sm_actor/64249.jpg",
  "https://st.kp.yandex.net/images/sm_actor/231411.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1202459.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1561921.jpg",
  "https://st.kp.yandex.net/images/sm_actor/886888.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1574780.jpg",
  "https://st.kp.yandex.net/images/sm_actor/231508.jpg",
  "https://st.kp.yandex.net/images/sm_actor/690012.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1358151.jpg",
  "https://st.kp.yandex.net/images/sm_actor/101749.jpg",
  "https://st.kp.yandex.net/images/sm_actor/238527.jpg",
  "https://st.kp.yandex.net/images/sm_actor/3873197.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1135358.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1440959.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1499491.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1818615.jpg",
  "https://st.kp.yandex.net/images/sm_actor/3027502.jpg",
  "https://st.kp.yandex.net/images/sm_actor/251184.jpg",
  "https://st.kp.yandex.net/images/sm_actor/231449.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2234782.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1577089.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1537279.jpg",
  "https://st.kp.yandex.net/images/sm_actor/25250.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1115855.jpg",
  "https://st.kp.yandex.net/images/sm_actor/432301.jpg",
  "https://st.kp.yandex.net/images/sm_actor/455876.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1705774.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1205093.jpg",
  "https://st.kp.yandex.net/images/sm_actor/3139249.jpg",
  "https://st.kp.yandex.net/images/sm_actor/224370.jpg",
  "https://st.kp.yandex.net/images/sm_actor/965223.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1140368.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1603586.jpg",
  "https://st.kp.yandex.net/images/sm_actor/230534.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1715230.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1543884.jpg",
  "https://st.kp.yandex.net/images/sm_actor/40159.jpg",
  "https://st.kp.yandex.net/images/sm_actor/162633.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2391885.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1055454.jpg",
  "https://st.kp.yandex.net/images/sm_actor/3290660.jpg",
  "https://st.kp.yandex.net/images/sm_actor/607682.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1629118.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1608272.jpg",
  "https://st.kp.yandex.net/images/sm_actor/558076.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2704915.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2807132.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1846148.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1601771.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1113820.jpg",
  "https://st.kp.yandex.net/images/sm_actor/483000.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1193736.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1693372.jpg",
  "https://st.kp.yandex.net/images/sm_actor/965217.jpg",
  "https://st.kp.yandex.net/images/sm_actor/238519.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1590391.jpg",
  "https://st.kp.yandex.net/images/sm_actor/231287.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1750665.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1821353.jpg",
  "https://st.kp.yandex.net/images/sm_actor/251186.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1628956.jpg",
  "https://st.kp.yandex.net/images/sm_actor/224368.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1857390.jpg",
  "https://st.kp.yandex.net/images/sm_actor/181144.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2305947.jpg",
  "https://st.kp.yandex.net/images/sm_actor/3372982.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1449894.jpg",
  "https://st.kp.yandex.net/images/sm_actor/673940.jpg",
  "https://st.kp.yandex.net/images/sm_actor/25248.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1813597.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1144155.jpg",
  "https://st.kp.yandex.net/images/sm_actor/238525.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1235079.jpg",
  "https://st.kp.yandex.net/images/sm_actor/3643612.jpg",
  "https://st.kp.yandex.net/images/sm_actor/740589.jpg",
  "https://st.kp.yandex.net/images/sm_actor/224576.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1551003.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1122331.jpg",
  "https://st.kp.yandex.net/images/sm_actor/3087165.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1705878.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1556971.jpg",
  "https://st.kp.yandex.net/images/sm_actor/677619.jpg",
  "https://st.kp.yandex.net/images/sm_actor/238532.jpg",
  "https://st.kp.yandex.net/images/sm_actor/231266.jpg",
  "https://st.kp.yandex.net/images/sm_actor/3007380.jpg",
  "https://st.kp.yandex.net/images/sm_actor/677661.jpg",
  "https://st.kp.yandex.net/images/sm_actor/476576.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1618898.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1625289.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1205144.jpg",
  "https://st.kp.yandex.net/images/sm_actor/681410.jpg",
  "https://st.kp.yandex.net/images/sm_actor/603499.jpg",
  "https://st.kp.yandex.net/images/sm_actor/464050.jpg",
  "https://st.kp.yandex.net/images/sm_actor/539454.jpg",
  "https://st.kp.yandex.net/images/sm_actor/231280.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1039999.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2394614.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2510834.jpg",
  "https://st.kp.yandex.net/images/sm_actor/238515.jpg",
  "https://st.kp.yandex.net/images/sm_actor/40157.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2696943.jpg",
  "https://st.kp.yandex.net/images/sm_actor/256836.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1193762.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1643257.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2496417.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1589095.jpg",
  "https://st.kp.yandex.net/images/sm_actor/245617.jpg",
  "https://st.kp.yandex.net/images/sm_actor/482994.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1603690.jpg",
  "https://st.kp.yandex.net/images/sm_actor/953572.jpg",
  "https://st.kp.yandex.net/images/sm_actor/281405.jpg",
  "https://st.kp.yandex.net/images/sm_actor/25244.jpg",
  "https://st.kp.yandex.net/images/sm_actor/703440.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1075124.jpg",
  "https://st.kp.yandex.net/images/sm_actor/185644.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1600482.jpg",
  "https://st.kp.yandex.net/images/sm_actor/3335983.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1193751.jpg",
  "https://st.kp.yandex.net/images/sm_actor/269763.jpg",
  "https://st.kp.yandex.net/images/sm_actor/298467.jpg",
  "https://st.kp.yandex.net/images/sm_actor/238713.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1208251.jpg",
  "https://st.kp.yandex.net/images/sm_actor/284624.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1039861.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1205146.jpg",
  "https://st.kp.yandex.net/images/sm_actor/573090.jpg",
  "https://st.kp.yandex.net/images/sm_actor/224537.jpg",
  "https://st.kp.yandex.net/images/sm_actor/231558.jpg",
  "https://st.kp.yandex.net/images/sm_actor/3936151.jpg",
  "https://st.kp.yandex.net/images/sm_actor/191587.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1815756.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1613529.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2286839.jpg",
  "https://st.kp.yandex.net/images/sm_actor/224365.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1746529.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2289203.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2672524.jpg",
  "https://st.kp.yandex.net/images/sm_actor/269499.jpg",
  "https://st.kp.yandex.net/images/sm_actor/277361.jpg",
  "https://st.kp.yandex.net/images/sm_actor/564278.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1601795.jpg",
  "https://st.kp.yandex.net/images/sm_actor/224607.jpg",
  "https://st.kp.yandex.net/images/sm_actor/261691.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2310826.jpg",
  "https://st.kp.yandex.net/images/sm_actor/231516.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1813400.jpg",
  "https://st.kp.yandex.net/images/sm_actor/464039.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1757987.jpg",
  "https://st.kp.yandex.net/images/sm_actor/251224.jpg",
  "https://st.kp.yandex.net/images/sm_actor/3262212.jpg",
  "https://st.kp.yandex.net/images/sm_actor/4150514.jpg",
  "https://st.kp.yandex.net/images/sm_actor/269734.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2275013.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1830367.jpg",
  "https://st.kp.yandex.net/images/sm_actor/224716.jpg",
  "https://st.kp.yandex.net/images/sm_actor/904647.jpg",
  "https://st.kp.yandex.net/images/sm_actor/238694.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1044664.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1641154.jpg",
  "https://st.kp.yandex.net/images/sm_actor/2454169.jpg",
  "https://st.kp.yandex.net/images/sm_actor/566942.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1821633.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1801495.jpg",
  "https://st.kp.yandex.net/images/sm_actor/573261.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1535359.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1663499.jpg",
  "https://st.kp.yandex.net/images/sm_actor/238541.jpg",
  "https://st.kp.yandex.net/images/sm_actor/473248.jpg",
  "https://st.kp.yandex.net/images/sm_actor/703441.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1308151.jpg",
  "https://st.kp.yandex.net/images/sm_actor/343964.jpg",
  "https://st.kp.yandex.net/images/sm_actor/969125.jpg",
  "https://st.kp.yandex.net/images/sm_actor/174285.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1487205.jpg",
  "https://st.kp.yandex.net/images/sm_actor/1358155.jpg",
  "https://st.kp.yandex.net/images/sm_actor/304325.jpg",
  "https://st.kp.yandex.net/images/sm_actor/231571.jpg",
  "https://st.kp.yandex.net/images/sm_actor/224619.jpg",
];
const full_name = [
  "Владимир Епифанцев",
  "Данила Козловский",
  "Александр Петров",
  "Константин Хабенский",
  "Светлана Ходченкова",
  "Дмитрий Назаров",
  "Любовь Аксёнова",
  "Дмитрий Нагиев",
  "Сергей Безруков",
  "Сергей Бурунов",
  "Антон Ельчин",
  "Юлия Александрова",
  "Кристина Асмус",
  "Пётр Фёдоров",
  "Владимир Машков",
  "Екатерина Вилкова",
  "Оксана Акиньшина",
  "Фёдор Бондарчук",
  "Катерина Шпица",
  "Паулина Андреева",
  "Юрий Быков",
  "Екатерина Климова",
  "Алексей Балабанов",
  "Евгений Цыганов",
  "Светлана Иванова",
  "Янина Студилина",
  "Елена Лядова",
  "Дарья Мельникова",
  "Алексей Чадов",
  "Елизавета Боярская",
  "Максим Матвеев",
  "Никита Михалков",
  "Иван Охлобыстин",
  "Ирина Старшенбаум",
  "Елена Подкаминская",
  "Анастасия Панина",
  "Владимир Яглыч",
  "Настасья Самбурская",
  "Александр Паль",
  "Алексей Серебряков",
  "Павел Деревянко",
  "Ингрид Олеринская",
  "Мария Горбань",
  "Юлия Пересильд",
  "Сергей Бодров мл.",
  "Аня Чиповская",
  "Владимир Вдовиченков",
  "Андрей Звягинцев",
  "Роман Курцын",
  "Юлия Снигирь",
  "Валерия Федорович",
  "Артур Смольянинов",
  "Анна Хилькевич",
  "София Каштанова",
  "Мария Кожевникова",
  "Юрий Колокольников",
  "Полина Максимова",
  "Ольга Серябкина",
  "Евгений Миронов",
  "Андрей Тарковский",
  "Жора Крыжовников",
  "Евгения Брик",
  "Илья Найшуллер",
  "Татьяна Арнтгольц",
  "Анна Михайловская",
  "Анна Старшенбаум",
  "Артём Ткаченко",
  "Виктор Хориняк",
  "Юлия Хлынина",
  "Сергей Романович",
  "Никита Панфилов",
  "Карина Разумовская",
  "Илья Любимов",
  "Гарик Харламов",
  "Марк Богатырев",
  "Елизавета Арзамасова",
  "Екатерина Гусева",
  "Сергей Светлаков",
  "Михаил Ефремов",
  "Илья Глинников",
  "Анфиса Вистингаузен",
  "Андрей Смоляков",
  "Таисия Вилкова",
  "Андрей Панин",
  "Ольга Кузьмина",
  "Андрей Миронов",
  "Зоя Бербер",
  "Лукерья Ильяшенко",
  "Аристарх Венес",
  "Светлана Устинова",
  "Олег Меньшиков",
  "Яна Троянова",
  "Лянка Грыу",
  "Иван Янковский",
  "Юлия Такшина",
  "Полина Гренц",
  "Настя Задорожная",
  "Александр Невский",
  "Валерия Гай Германика",
  "Иван Жидков",
  "Татьяна Бабенкова",
  "Денис Шведов",
  "Анастасия Сиваева",
  "Маргарита Левиева",
  "Михаил Пореченков",
  "Мария Миронова",
  "Аглая Тарасова",
  "Алексей Бардуков",
  "Андрей Мерзликин",
  "Александр Ильин мл.",
  "Никита Ефремов",
  "Агния Кузнецова",
  "Иван Ургант",
  "Константин Крюков",
  "Ирина Пегова",
  "Дмитрий Дюжев",
  "Рената Литвинова",
  "Владимир Жеребцов",
  "Яна Кошкина",
  "Алина Ланина",
  "Ксения Раппопорт",
  "Андрей Кончаловский",
  "Риналь Мухаметов",
  "Владимир Зайцев",
  "Михаил Галустян",
  "Пётр Иващенко",
  "Даниил Вахрушев",
  "Екатерина Старшова",
  "Дарья Мороз",
  "Мария Шалаева",
  "Ирина Вилкова",
  "Кирилл Серебренников",
  "Константин Лавроненко",
  "Сергей Бодров",
  "Анна Уколова",
  "Евгений Пронин",
  "Леонид Куравлёв",
  "Мария Берсенева",
  "Глеб Калюжный",
  "Павел Воля",
  "Фёдор Добронравов",
  "Ян Цапник",
  "Владислав Галкин",
  "Глафира Тарханова",
  "Александр Демьяненко",
  "Рина Гришина",
  "Леонид Бичевин",
  "Денис Никифоров",
  "Александр Абдулов",
  "Евгений Стычкин",
  "Диана Пожарская",
  "Леонид Гайдай",
  "Роман Каримов",
  "Дмитрий Шаракоис",
  "Юра Борисов",
  "Александр Яценко",
  "Алексей Воробьёв",
  "Мария Поезжаева",
  "Семён Трескунов",
  "Даниил Страхов",
  "Анастасия Заворотнюк",
  "Иван Стебунов",
  "Денис Косяков",
  "Максим Аверин",
  "Мария Машкова",
  "Валентина Мазунина",
  "Алексей Макаров",
  "Анфиса Черных",
  "Мария Порошина",
  "Николай Наумов",
  "Елена Панова",
  "Оксана Сидоренко",
  "Ксения Лукьянчикова",
  "Мария Аронова",
  "Наталья Земцова",
  "Александра Ребенок",
  "Чулпан Хаматова",
  "Анна Цуканова-Котт",
  "Дмитрий Марьянов",
  "Анна Снаткина",
  "Татьяна Шитова",
  "Наталья Бардо",
  "Егор Бероев",
  "Гела Месхи",
  "Ольга Дибцева",
  "Сергей Чирков",
  "Елена Беркова",
  "Мария Иващенко",
  "Олеся Судзиловская",
  "Александр Робак",
  "Даша Чаруша",
  "Дарья Сагалова",
  "Евгений Леонов",
  "Мария Куликова",
  "Вера Алентова",
  "Иван Макаревич",
  "Антон Шагин",
  "Владимир Сычев",
  "Любовь Толкалина",
  "Эльдар Рязанов",
];
const discription = [
  "актер, режиссер, актер дубляжа, сценарист, продюсер, оператор. 51 год",
  "актер, продюсер, режиссер, актер дубляжа, сценарист. 38 лет",
  "актер, режиссер, сценарист, продюсер, актер дубляжа. 34 года",
  "актер, актер дубляжа, режиссер, сценарист, продюсер. 51 год",
  "актриса, режиссер, сценарист, продюсер, оператор, актриса дубляжа. 40 лет",
  "актер, актер дубляжа. 65 лет",
  "актриса, актриса дубляжа. 33 года",
  "актер, актер дубляжа. 56 лет",
  "актер, актер дубляжа, продюсер, режиссер, сценарист. 49 лет",
  "актер дубляжа, актер. 46 лет",
  "актер. 27 лет",
  "актриса, оператор. 41 год",
  "актриса, актриса дубляжа. 35 лет",
  "актер, актер дубляжа, сценарист, режиссер, композитор, монтажер, продюсер. 41 год",
  "актер, режиссер, продюсер, сценарист, актер дубляжа. 59 лет",
  "актриса. 38 лет",
  "актриса. 36 лет",
  "актер, продюсер, режиссер, актер дубляжа, сценарист. 56 лет",
  "актриса, актриса дубляжа. 37 лет",
  "актриса, сценарист, режиссер, продюсер. 34 года",
  "актер, режиссер, сценарист, композитор, монтажер, продюсер. 41 год",
  "актриса, актриса дубляжа. 45 лет",
  "режиссер, сценарист, актер, продюсер, актер дубляжа. 54 года",
  "актер, режиссер, сценарист, продюсер, композитор, актер дубляжа. 44 года",
  "актриса, актриса дубляжа. 37 лет",
  "актриса. 37 лет",
  "актриса, актриса дубляжа. 42 года",
  "актриса, актриса дубляжа. 31 год",
  "актер, сценарист, актер дубляжа, режиссер, продюсер. 41 год",
  "актриса, актриса дубляжа. 37 лет",
  "актер, актер дубляжа. 40 лет",
  "актер, режиссер, продюсер, сценарист, директор фильма. 77 лет",
  "актер, сценарист, режиссер, актер дубляжа, продюсер. 56 лет",
  "актриса, продюсер, актриса дубляжа. 31 год",
  "актриса. 44 года",
  "актриса. 40 лет",
  "актер, актер дубляжа. 40 лет",
  "актриса, актриса дубляжа, продюсер. 36 лет",
  "актер, актер дубляжа. 34 года",
  "актер, актер дубляжа. 58 лет",
  "актер, актер дубляжа. 46 лет",
  "актриса. 31 год",
  "актриса. 36 лет",
  "актриса. 38 лет",
  "актер, сценарист, режиссер. 30 лет",
  "актриса, актриса дубляжа. 35 лет",
  "актер, актер дубляжа. 51 год",
  "режиссер, актер, сценарист, продюсер, монтажер. 59 лет",
  "актер, продюсер, актер дубляжа. 38 лет",
  "актриса, актриса дубляжа. 39 лет",
  "актриса. 30 лет",
  "актер, актер дубляжа. 39 лет",
  "актриса, актриса дубляжа. 36 лет",
  "актриса. 35 лет",
  "актриса, актриса дубляжа. 38 лет",
  "актер, актер дубляжа, продюсер. 42 года",
  "актриса, актриса дубляжа. 33 года",
  "актриса, композитор. 38 лет",
  "актер, продюсер, актер дубляжа, сценарист. 56 лет",
  "сценарист, режиссер, актер, монтажер, художник, директор фильма. 54 года",
  "сценарист, режиссер, продюсер, художник. 44 года",
  "актриса. 40 лет",
  "режиссер, актер, продюсер, сценарист, композитор. 39 лет",
  "актриса, актриса дубляжа. 41 год",
  "актриса. 34 года",
  "актриса, актриса дубляжа, продюсер. 34 года",
  "актер. 41 год",
  "актер, актер дубляжа. 33 года",
  "актриса, актриса дубляжа. 31 год",
  "актер. 30 лет",
  "актер, актер дубляжа. 44 года",
  "актриса, актриса дубляжа. 40 лет",
  "актер, актер дубляжа. 46 лет",
  "актер, актер дубляжа, сценарист, продюсер, композитор. 42 года",
  "актер. 38 лет",
  "актриса, актриса дубляжа, сценарист. 28 лет",
  "актриса, актриса дубляжа. 46 лет",
  "актер, продюсер, сценарист, актер дубляжа. 45 лет",
  "актер, сценарист, актер дубляжа. 59 лет",
  "актер, режиссер, сценарист, продюсер. 38 лет",
  "актриса. 23 года",
  "актер. 64 года",
  "актриса, актриса дубляжа. 26 лет",
  "актер, режиссер, продюсер. 50 лет",
  "актриса, актриса дубляжа. 35 лет",
  "актер, режиссер. 46 лет",
  "актриса, актриса дубляжа. 35 лет",
  "актриса. 33 года",
  "актер, продюсер. 33 года",
  "актриса, сценарист, продюсер, режиссер. 41 год",
  "актер, актер дубляжа, режиссер. 62 года",
  "актриса, режиссер, сценарист. 50 лет",
  "актриса, режиссер, сценарист, продюсер. 35 лет",
  "актер. 32 года",
  "актриса. 42 года",
  "актриса, актриса дубляжа. 28 лет",
  "актриса. 37 лет",
  "актер, продюсер, сценарист, актер дубляжа, режиссер. 51 год",
  "режиссер, актриса, сценарист, оператор, продюсер, монтажер. 39 лет",
  "актер. 39 лет",
  "актриса, актриса дубляжа. 31 год",
  "актер, актер дубляжа. 41 год",
  "актриса, актриса дубляжа. 31 год",
  "актриса. 43 года",
  "актер, актер дубляжа, продюсер, режиссер. 54 года",
  "актриса, актриса дубляжа. 49 лет",
  "актриса. 29 лет",
  "актер, актер дубляжа. 38 лет",
  "актер, актер дубляжа, режиссер. 50 лет",
  "актер, режиссер, композитор. 39 лет",
  "актер, актер дубляжа. 34 года",
  "актриса. 37 лет",
  "актер, продюсер, сценарист, актер дубляжа. 45 лет",
  "актер, актер дубляжа. 38 лет",
  "актриса, актриса дубляжа. 44 года",
  "актер, режиссер, актер дубляжа, сценарист. 44 года",
  "актриса, сценарист, режиссер, продюсер, монтажер, актриса дубляжа. 56 лет",
  "актер. 39 лет",
  "актриса. 33 года",
  "актриса. 34 года",
  "актриса, актриса дубляжа, режиссер, сценарист. 49 лет",
  "сценарист, режиссер, продюсер, актер, актер дубляжа. 85 лет",
  "актер, сценарист. 33 года",
  "актер дубляжа, актер. 64 года",
  "актер, актер дубляжа, продюсер. 43 года",
  "актер дубляжа, актер, продюсер, режиссер дубляжа. 46 лет",
  "актер. 31 год",
  "актриса. 21 год",
  "актриса, продюсер, актриса дубляжа, режиссер. 39 лет",
  "актриса, режиссер, сценарист, продюсер. 42 года",
  "актриса, режиссер, сценарист, продюсер. 37 лет",
  "режиссер, сценарист, художник, актер, продюсер. 53 года",
  "актер, актер дубляжа. 62 года",
  "сценарист, режиссер, продюсер, актер. 74 года",
  "актриса. 45 лет",
  "актер, продюсер. 42 года",
  "актер, актер дубляжа. 85 лет",
  "актриса, актриса дубляжа. 41 год",
  "актер. 24 года",
  "актер, актер дубляжа, сценарист. 44 года",
  "актер, актер дубляжа, продюсер. 61 год",
  "актер, актер дубляжа. 54 года",
  "актер, актер дубляжа. 38 лет",
  "актриса. 39 лет",
  "актер дубляжа, актер. 62 года",
  "актриса, актриса дубляжа, продюсер. 35 лет",
  "актер. 38 лет",
  "актер. 45 лет",
  "актер, сценарист, режиссер, продюсер, актер дубляжа. 54 года",
  "актер, актер дубляжа, режиссер. 48 лет",
  "актриса. 31 год",
  "режиссер, сценарист, актер. 70 лет",
  "режиссер, сценарист, актер, композитор, продюсер, монтажер. 38 лет",
  "актер. 37 лет",
  "актер. 30 лет",
  "актер. 46 лет",
  "актер, композитор, актер дубляжа, режиссер, сценарист, монтажер, продюсер. 35 лет",
  "актриса. 34 года",
  "актер, режиссер, сценарист, актер дубляжа, продюсер. 23 года",
  "актер, актер дубляжа. 47 лет",
  "актриса, актриса дубляжа. 52 года",
  "актер, режиссер, продюсер, сценарист. 41 год",
  "актер, сценарист, продюсер. 39 лет",
  "актер, режиссер, актер дубляжа. 47 лет",
  "актриса, продюсер, сценарист. 38 лет",
  "актриса. 35 лет",
  "актер. 51 год",
  "актриса. 27 лет",
  "актриса, актриса дубляжа. 49 лет",
  "актер, актер дубляжа. 41 год",
  "актриса. 45 лет",
  "актриса, актриса дубляжа. 36 лет",
  "актриса. 30 лет",
  "актриса, актриса дубляжа. 51 год",
  "актриса, сценарист, продюсер. 35 лет",
  "актриса, актриса дубляжа, сценарист. 43 года",
  "актриса, актриса дубляжа. 47 лет",
  "актриса, режиссер, актриса дубляжа, сценарист, продюсер. 33 года",
  "актер, сценарист. 47 лет",
  "актриса, актриса дубляжа. 39 лет",
  "актриса дубляжа, актриса. 47 лет",
  "актриса. 35 лет",
  "актер, актер дубляжа. 45 лет",
  "актер. 37 лет",
  "актриса, режиссер, сценарист, продюсер. 36 лет",
  "актер. 39 лет",
  "актриса. 38 лет",
  "актриса дубляжа, актриса. 31 год",
  "актриса, актриса дубляжа. 49 лет",
  "актер, продюсер, режиссер, оператор. 49 лет",
  "актриса, композитор, режиссер, сценарист, продюсер, актриса дубляжа. 42 года",
  "актриса. 37 лет",
  "актер. 67 лет",
  "актриса, актриса дубляжа. 45 лет",
  "актриса, актриса дубляжа. 81 год",
  "актер, художник, композитор, режиссер, актер дубляжа. 35 лет",
  "актер, актер дубляжа. 39 лет",
  "актер, продюсер. 51 год",
  "актриса, актриса дубляжа. 45 лет",
  "режиссер, сценарист, актер. 88 лет",
];

const DOB = [
  "1971",
  "1985",
  "1989",
  "1972",
  "1983",
  "1957",
  "1990",
  "1967",
  "1973",
  "1977",
  "1989 – 2016",
  "1982",
  "1988",
  "1982",
  "1963",
  "1984",
  "1987",
  "1967",
  "1985",
  "1988",
  "1981",
  "1978",
  "1959 – 2013",
  "1979",
  "1985",
  "1985",
  "1980",
  "1992",
  "1981",
  "1985",
  "1982",
  "1945",
  "1966",
  "1992",
  "1979",
  "1983",
  "1983",
  "1987",
  "1988",
  "1964",
  "1976",
  "1992",
  "1986",
  "1984",
  "1971 – 2002",
  "1987",
  "1971",
  "1964",
  "1985",
  "1983",
  "1992",
  "1983",
  "1986",
  "1987",
  "1984",
  "1980",
  "1989",
  "1985",
  "1966",
  "1932 – 1986",
  "1979",
  "1981 – 2022",
  "1983",
  "1982",
  "1988",
  "1989",
  "1982",
  "1990",
  "1992",
  "1992",
  "1979",
  "1983",
  "1977",
  "1981",
  "1984",
  "1995",
  "1976",
  "1977",
  "1963",
  "1984",
  "1999",
  "1958",
  "1996",
  "1962 – 2013",
  "1987",
  "1941 – 1987",
  "1987",
  "1989",
  "1989",
  "1982",
  "1960",
  "1973",
  "1987",
  "1990",
  "1980",
  "1994",
  "1985",
  "1971",
  "1984",
  "1983",
  "1991",
  "1981",
  "1991",
  "1980",
  "1969",
  "1973",
  "1994",
  "1984",
  "1973",
  "1983",
  "1988",
  "1985",
  "1978",
  "1985",
  "1978",
  "1978",
  "1967",
  "1983",
  "1990",
  "1989",
  "1974",
  "1937",
  "1989",
  "1958",
  "1979",
  "1976",
  "1992",
  "2001",
  "1983",
  "1981",
  "1986",
  "1969",
  "1961",
  "1948",
  "1978",
  "1980",
  "1936 – 2022",
  "1981",
  "1998",
  "1979",
  "1961",
  "1968",
  "1971 – 2010",
  "1983",
  "1937 – 1999",
  "1987",
  "1984",
  "1977",
  "1953 – 2008",
  "1974",
  "1992",
  "1923 – 1993",
  "1984",
  "1986",
  "1992",
  "1977",
  "1988",
  "1989",
  "1999",
  "1976",
  "1971",
  "1981",
  "1984",
  "1975",
  "1985",
  "1988",
  "1972",
  "1996",
  "1973",
  "1982",
  "1977",
  "1987",
  "1993",
  "1972",
  "1987",
  "1980",
  "1975",
  "1989",
  "1969 – 2017",
  "1983",
  "1975",
  "1988",
  "1977",
  "1986",
  "1986",
  "1983",
  "1985",
  "1991",
  "1974",
  "1973",
  "1980",
  "1985",
  "1926 – 1994",
  "1977",
  "1942",
  "1987",
  "1984",
  "1971",
  "1978",
  "1927 – 2015",
];

const mergedArray = avatar.map(function (element, index) {
  return {
    avatar: element,
    full_name: full_name[index],
    description: discription[index],
    DOB: DOB[index],
  };
});

const json = JSON.stringify(mergedArray);
console.log(json);
